name: daily-signal-bot
on:
  schedule:
    # 10:40 UTC ≈ 16:10 IST (post-market recap), weekdays
    - cron: "40 10 * * 1-5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TICKERS: ${{ secrets.TICKERS }}
          LOOKBACK_DAYS: "180"
          MA_WINDOW: "20"
          RSI_WINDOW: "14"
          RSI_BUY: "55"
          RSI_SELL: "45"
        run: python main.py
